// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccgfnfzswpyaioncdjap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjZ2ZuZnpzd3B5YWlvbmNkamFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0NDkxNDUsImV4cCI6MjA3ODAyNTE0NX0.G2Vfcxsr7l7JyxahYXvY1d6-qbu-EZc46tu_WkdDj2k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});